### ISSUE TITLE
Cmake fail - Ubuntu 20.04

### ISSUE THREAD

**Issue by maxdrash** [exeldro/obs-media-controls#6]
Hello @exeldro !

I try to compile on Ubuntu 20.04 but I got some errors:

**obs-studio-25.0.8/plugins/obs-media-controls-022/media-controls.hpp:11:10: fatal error: ui_MediaControls.h: Aucun fichier ou dossier de ce type
   11 | #include "ui_MediaControls.h"**
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
**make[2]: *** [plugins/obs-media-controls-022/CMakeFiles/media-controls.dir/build.make:80: plugins/obs-media-controls-022/CMakeFiles/media-controls.dir/media-controls.cpp.o] Error 1
make[2]: *** Attente des tâches non terminées....**
[ 64%] Building CXX object plugins/obs-ndi-491/CMakeFiles/obs-ndi.dir/src/obs-ndi.cpp.o
**obs-studio-25.0.8/plugins/obs-media-controls-022/media-control.cpp:9:10: fatal error: ../../item-widget-helpers.hpp: Aucun fichier ou dossier de ce type
    9 | #include "../../item-widget-helpers.hpp"**
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

I can't find ui_MediaControls.h file in your repo.
Where is my mistake ?

Tx !

**Comment by exeldro** [comment]
That file should be made by cmake from MediaControls.ui

**Comment by maxdrash** [comment]
@tt2468 any help please ?

**Comment by maxdrash** [comment]
Sorry, I've placed obs-media-controls in plugins/ instead of UI/frontend-plugins/.
Compilation is OK now, my fault ;)

That's a great job thank you !
